### ISSUE TITLE
Unable to load db manager

### ISSUE THREAD

**Issue by cbt2016** [lionixevolve/GraphQLSuiteCRM#1]
Upon integrating GraphqlSuiteCRM in our project ,we added new schemas and generated new mapping using doctrine .The issue happens when we try to regenerate entities using the command : 

> php vendor/bin/doctrine orm:generate-entities  --regenerate-entities --no-backup ./

we get the following error : Cannot load DB manager .
I would appreciate it if you could provide me more infos about this issue .
Thank you

**Comment by mrbarletta** [comment]
Hi @cbt2016 -  could you please install the latest version from composer? we moved away from generating entities and implemented an on the fly entity definition based on SuiteCRM vardefs.

**Comment by cbt2016** [comment]
hello @mrbarletta ,where can i find the latest version ? can i run on apache server using docker image ?

**Comment by mrbarletta** [comment]
@cbt2016 sorry  the correct word was COMPOSER, install the latest version using composer, not docker :)

**Comment by cbt2016** [comment]
this is the versions i am using with composer : 

> "require": {
        "slim/slim": "~3.8",
        "codeguy/upload": "dev-master",
        "youshido/graphql": "^1.5",
        "monolog/monolog": "^1.23",
        "doctrine/orm": "*",
        "symfony/yaml": "3.4.x-dev"
    }
should i install which new version of which package using composer

**Comment by mrbarletta** [comment]
Having minimum required stability in dev you can do 
`composer require lionixevolve/graphqlsuitecrm:v0.9.3`

**Comment by cbt2016** [comment]
Upon installing new version ,effectively now it is placed inside vendor/lionixevolve/graphqlsuitecrm.I have added new schema type .Should i regenerate it using doctrine or is it automatized in the new version ?.Thank you so much

**Comment by mrbarletta** [comment]
Nothing should be done, you can use it right away. 
Check the readme I added a few queries as an example.

**Comment by cbt2016** [comment]
It Works perfectly .thank you very much for your answers.I Really appreciate the efforts you have put in elaborating such a professional solution
