### ISSUE TITLE
Additional field not working in custom Mutation (using custom module)

### ISSUE THREAD

**Issue by rigalpatel001** [lionixevolve/GraphQLSuiteCRM#15]
Hello,

I have checked an additional field not working with the mutation . field working only if it's available on the module. How to pass the relational module field in mutation?

We have checked crmhelper.php files and change code but it's not working.

Thanks

**Comment by mrbarletta** [comment]
Extra fields in the relation is not something supported and I don't know if it will be supported as its not very common in SuiteCRM to save data in the relation. Except for opportunities contacts roles I remember no other extra relationship field so advice against that.
