### ISSUE TITLE
How to pass value in SuiteCRMSchema file

### ISSUE THREAD

**Issue by ankitpatelinitio** [lionixevolve/GraphQLSuiteCRM#16]
Hello,

  I have to pass value from rest.php to SuiteCRMSchema.php when declaring an object of that class. I tried to pass value from rest.php but It gives me an error. So how can I pass value from rest.php file to SuiteCRMSchema.php?

Please give me a solution.

Thanks.

**Comment by mrbarletta** [comment]
Hi @ankitpatelinitio - you shouldn't be editing any file in the vendor folder, both can be overridden as it is shown here: 
https://github.com/lionixevolve/GraphQLSuiteCRM#extendingcustomizing-suitecrm-graphql-schema

Furthermore, if you are trying to make the rest functionality interact with the graphql endpoint, that is not what graphql is made for, everything related to graphql has to be sent in a post request with graphql markup.
