### ISSUE TITLE
How to get records by descending order?

### ISSUE THREAD

**Issue by ankitpatelinitio** [lionixevolve/GraphQLSuiteCRM#8]
How to get records by descending order from graphql query. I tried to use order parameter with the field but it gave me records by ascending orders.

Thanks

**Comment by mrbarletta** [comment]
Hi @ankitpatelinitio  - just add DESC to the order field
```
query {
  contacts(order:"first_name desc"){
   first_name
  }
}
``` 
![image](https://user-images.githubusercontent.com/2429244/54869385-29cb5700-4d5d-11e9-8fd2-cf30436622e2.png)

**Comment by ankitpatelinitio** [comment]
Thanks, @mrbarletta , I tried this solution and it's working fine.
